### PR TITLE
Create MassIncrease.cfg

### PR DESCRIPTION
**Pull request by JamesErvin-5**
Did it!

### CODE REVIEW

**Comment by JamesErvin-5** [comment]
Doubles everything's weight.

**Comment by staticalliam7** [comment]
Wait whatttttt
Literally 4 lines? Impressive.

**Comment by staticalliam7** [comment]
Also, I'm a dumbass and got distracted and didn't merge

**Comment by JamesErvin-5** [comment]
> Wait whatttttt Literally 4 lines? Impressive.

Yep, once you learn some tricks, everything falls into place.

**Pull request merged**
